apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "dynamic-dns-updater.fullname" . }}
  labels:
    app: {{ template "dynamic-dns-updater.name" . }}
    chart: {{ template "dynamic-dns-updater.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  concurrencyPolicy: "{{ .Values.cronjob.concurrencyPolicy }}"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ template "dynamic-dns-updater.name" . }}
            release: {{ .Release.Name }}
        spec:
          restartPolicy: OnFailure
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
              - name: USERNAME
                valueFrom:
                  secretKeyRef:
                    name: {{ template "dynamic-dns-updater.fullname" . }}
                    key: username
              - name: PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ template "dynamic-dns-updater.fullname" . }}
                    key: password
              - name: DOMAIN
                value: {{ .Values.updater.domain | quote }}
              - name: SUB_DOMAIN
                value: {{ .Values.updater.subDomain | quote }}
              - name: CPANEL_URL
                value: {{ .Values.updater.cpanelUrl | quote }}
              resources:
{{ toYaml .Values.resources | indent 16 }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
{{ toYaml . | indent 12 }}
          {{- end }}
