apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dynamic-dns-updater.fullname" . }}
  labels:
    app: {{ template "dynamic-dns-updater.name" . }}
    chart: {{ template "dynamic-dns-updater.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  username: {{ .Values.updater.username | b64enc }}
  password: {{ .Values.updater.password | b64enc }}
